baseURL = 'https://macworks.dev/'
title = 'MacWorks'
theme = 'hugo-book'
defaultContentLanguage = 'en'

disablePathToLower = true
enableGitInfo = false

[languages]
[languages.en]
languageName = 'English'
weight = 1

[markup]
[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
startLevel = 1

[markup.highlight]
style = 'base16-snazzy'

[params]
BookTheme = 'auto'
BookSection = 'docs'
BookSearch = true
BookToC = true
BookComments = false
