baseURL = 'https://nickyfoto.github.io/book/'
title = 'My Book'
theme = 'hugo-book'

disablePathToLower = true
enableGitInfo = false

[markup]
[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
startLevel = 1

[markup.highlight]
style = 'base16-snazzy'

[params]
BookTheme = 'auto'
BookSection = 'docs'
BookSearch = true
BookToC = true
BookComments = false
